name: CI

on:
  push:
    branches: [ "master" ]


env:
  SCHEMATIC_IMG_PATH: docs/images/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
        sudo apt update --yes
        sudo apt install --install-recommends --yes kicad
    - name: Generate the schematic image
      run: kicad-cli sch export svg hardware/Telebotomy.kicad_sch -o $SCHEMATIC_IMG_PATH
    - name: Push changes
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        add: .
        message: 'Updates Schematic Image'